name: Build

on:
  push:
    branches: [ develop ]
  pull_request:
    types: closed
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Decrypt google-services.json
      run: |
        chmod +x ./.github/scripts/decrypt_key.sh
        ./.github/scripts/decrypt_key.sh
      env:
        FIREBASE_PASSPHRASE: ${{ secrets.FIREBASE_PASSPHRASE }}
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Run usermanagerlib tests
      run: ./gradlew :usermanagerlib:test
    
    - name: Build usermanagerlib
      run: ./gradlew :usermanagerlib:assembleRelease
    
    - name: Upload usermanagerlib
      uses: actions/upload-artifact@v1.0.0
      with:
        name: usermanagerlib-release.aar
        path: ./usermanagerlib/build/outputs/aar

    - name: Run communitymanager tests
      run: ./gradlew :communitymanager:test

    - name: Build communitymanager
      run: ./gradlew :communitymanager:assembleRelease

    - name: Upload communitymanager
      uses: actions/upload-artifact@v1.0.0
      with:
        name: communitymanager-release.aar
        path: ./communitymanager/build/outputs/aar

    - name: Run httptools tests
      run: ./gradlew :httptools:test

    - name: Build httptools
      run: ./gradlew :httptools:assembleRelease

    - name: Upload httptools
      uses: actions/upload-artifact@v1.0.0
      with:
        name: httptools-release.aar
        path: ./httptools/build/outputs/aar
      
